plugins {
    id 'com.android.application'
}

android {
    namespace 'com.indrolend.digitalbreakdown'
    compileSdk 35

    defaultConfig {
        applicationId 'com.indrolend.digitalbreakdown.native'
        minSdk 27
        targetSdk 35
        versionCode 1
        versionName '0.1-native'

        externalNativeBuild {
            cmake {
                cppFlags '-std=c++17 -Wall -Wextra'
            }
        }

        ndk {
            abiFilters 'armeabi-v7a'
        }
    }

    externalNativeBuild {
        cmake {
            path 'src/main/cpp/CMakeLists.txt'
        }
    }
}
