#include "Game.hpp"
#include "gameplay/PhoneBody.hpp"

#include <cmath>
#include <cstdio>
#include <memory>
#include <vector>

namespace {
constexpr float Dt=1.0f/60.0f;
void input(Game& game,float x,float z,bool vacuum=false,bool jump=false,bool melee=false,bool shoot=false){
    // The combined lab puts the rock beside the wedge. Once a case starts on
    // the rock, isolate its all-direction sweep from the wedge-side contract.
    if(game.state().rockSupportCount>0&&game.state().player.pos.x>3.5f)game.networkMutableState().slopeSupportCount=0;
    game.setTouchControls(x,z,0,0,vacuum,false,jump,melee,shoot,false);game.update(Dt);
}
void placeOnSlope(Game& game,float x,float z){auto& state=game.networkMutableState();const auto sample=sampleSlopeSupport(state.slopeSupports[0],x,z);state.player.pos={x,sample.height+0.08f,z};state.player.vel={};state.player.jumpVel=0;state.player.grounded=true;state.player.battery=100;state.camera.yaw=0;}
bool near(float a,float b,float tolerance=0.025f){return std::fabs(a-b)<=tolerance;}
float horizontalSpeed(const Vec3& velocity){return std::sqrt(velocity.x*velocity.x+velocity.z*velocity.z);}
float denseRockHeight(const faceted_rock::Support& rock,float x,float z,float radius){float height=-1.0f;for(int ring=0;ring<=3;++ring){const float r=radius*static_cast<float>(ring)/3.0f;const int steps=ring==0?1:96;for(int step=0;step<steps;++step){const float angle=6.283185307f*static_cast<float>(step)/static_cast<float>(steps);const auto sample=faceted_rock::sampleEnvelope(rock,x+std::cos(angle)*r,z+std::sin(angle)*r);if(sample.inside)height=std::max(height,sample.height);}}return height;}
std::vector<Vec3> walkableRockFaceCenters(const faceted_rock::Support& rock){
    const auto mesh=faceted_rock::makeMesh(rock.prop,rock.roomSeed,rock.roomIndex,rock.propIndex);std::vector<Vec3> centers;
    for(int vertex=0;vertex+2<mesh.vertexCount;vertex+=3){const auto point=[&](int index){return Vec3{mesh.positions[index*3],mesh.positions[index*3+1],mesh.positions[index*3+2]};};const Vec3 a=point(vertex),b=point(vertex+1),c=point(vertex+2);if(faceted_rock::triangleWalkable(faceted_rock::faceNormal(a,b,c)))centers.push_back((a+b+c)*(1.0f/3.0f));}
    return centers;
}
struct PhoneWorldBounds{float bottom=0.0f;float horizontalRadius=0.0f;};
PhoneWorldBounds phoneWorldBounds(const GameState& state){
    const Vec3 axisX=rotate(state.phoneTransform.orientation,{1,0,0});
    const Vec3 axisY=rotate(state.phoneTransform.orientation,{0,1,0});
    const Vec3 axisZ=rotate(state.phoneTransform.orientation,{0,0,1});
    const float halfX=PHONE_BODY_WIDTH*state.phoneVisual.bodyScale.x*0.5f;
    const float halfY=PHONE_BODY_HEIGHT*state.phoneVisual.bodyScale.y*0.5f;
    const float halfZ=PHONE_BODY_DEPTH*state.phoneVisual.bodyScale.z*0.5f;
    const float extentX=std::abs(axisX.x)*halfX+std::abs(axisY.x)*halfY+std::abs(axisZ.x)*halfZ;
    const float extentY=std::abs(axisX.y)*halfX+std::abs(axisY.y)*halfY+std::abs(axisZ.y)*halfZ;
    const float extentZ=std::abs(axisX.z)*halfX+std::abs(axisY.z)*halfY+std::abs(axisZ.z)*halfZ;
    return {state.phoneTransform.position.y-extentY,std::sqrt(extentX*extentX+extentZ*extentZ)};
}
}

int main(){
    Game ascent;ascent.debugStartSlopeLab();const auto fixture=ascent.state().slopeSupports[0];
    if(!ascent.state().slopeLab||ascent.state().slopeSupportCount!=1||ascent.state().debug.colliderCount!=1||classifySupport(fixture)!=SupportClassification::TraversableSlope){std::fprintf(stderr,"SLOPE_FIXTURE_FAIL authority\n");return 1;}
    bool crossedSlope=false,reachedPlateau=false;float previousY=ascent.state().player.pos.y;Vec3 previousCamera=ascent.state().camera.pos;
    for(int frame=0;frame<600;++frame){input(ascent,0,1);const auto& p=ascent.state().player;const Vec3 cameraDelta=ascent.state().camera.pos-previousCamera;if(!std::isfinite(ascent.state().camera.pos.x)||!std::isfinite(ascent.state().camera.pos.y)||!std::isfinite(ascent.state().camera.pos.z)||(frame>0&&length(cameraDelta)>1.0f)||horizontalSpeed(p.vel)>7.0f){std::fprintf(stderr,"SLOPE_FIXTURE_FAIL bounded camera/speed frame=%d\n",frame);return 1;}previousCamera=ascent.state().camera.pos;if(p.pos.z<fixture.maxZ&&p.pos.z>fixture.minZ){const auto support=sampleSlopeSupport(fixture,p.pos.x,p.pos.z);crossedSlope=true;if(!p.grounded||!near(p.pos.y,support.height+0.08f)||p.pos.y+0.001f<previousY){std::fprintf(stderr,"SLOPE_FIXTURE_FAIL ascent frame=%d pos=(%.3f,%.3f,%.3f)\n",frame,p.pos.x,p.pos.y,p.pos.z);return 1;}}previousY=p.pos.y;if(p.pos.z<fixture.minZ-0.3f){reachedPlateau=p.grounded&&near(p.pos.y,1.68f);break;}}
    if(!crossedSlope||!reachedPlateau){const auto& p=ascent.state().player;std::fprintf(stderr,"SLOPE_FIXTURE_FAIL seam ascent crossed=%d plateau=%d pos=(%.3f,%.3f,%.3f) grounded=%d\n",crossedSlope?1:0,reachedPlateau?1:0,p.pos.x,p.pos.y,p.pos.z,p.grounded?1:0);return 1;}

    Game stop;stop.debugStartSlopeLab();placeOnSlope(stop,0,7);for(int i=0;i<45;++i)input(stop,0,1);for(int i=0;i<120;++i)input(stop,0,0);const auto stopped=stop.state().player;const auto stoppedSupport=sampleSlopeSupport(fixture,stopped.pos.x,stopped.pos.z);if(!stopped.grounded||horizontalSpeed(stopped.vel)>0.02f||!near(stopped.pos.y,stoppedSupport.height+0.08f)){std::fprintf(stderr,"SLOPE_FIXTURE_FAIL stopping speed=%.3f\n",horizontalSpeed(stopped.vel));return 1;}

    Game reverse;reverse.debugStartSlopeLab();placeOnSlope(reverse,0,7);for(int i=0;i<24;++i)input(reverse,0,1);const float uphillZ=reverse.state().player.pos.z;for(int i=0;i<24;++i)input(reverse,0,-1);if(reverse.state().player.vel.z<=0||reverse.state().player.pos.z<=uphillZ){std::fprintf(stderr,"SLOPE_FIXTURE_FAIL reversal velZ=%.3f\n",reverse.state().player.vel.z);return 1;}

    Game downhill;downhill.debugStartSlopeLab();placeOnSlope(downhill,0,3);for(int i=0;i<45;++i)input(downhill,0,-1);if(!downhill.state().player.grounded||downhill.state().player.pos.z<=3.5f){std::fprintf(stderr,"SLOPE_FIXTURE_FAIL downhill\n");return 1;}
    Game lateral;lateral.debugStartSlopeLab();placeOnSlope(lateral,0,7);for(int i=0;i<30;++i)input(lateral,1,0);if(!lateral.state().player.grounded||lateral.state().player.pos.x<0.5f||std::fabs(lateral.state().player.pos.z-7)>0.05f){std::fprintf(stderr,"SLOPE_FIXTURE_FAIL lateral pos=(%.3f,%.3f)\n",lateral.state().player.pos.x,lateral.state().player.pos.z);return 1;}

    Game jump;jump.debugStartSlopeLab();placeOnSlope(jump,0,7);input(jump,0,0,false,true);if(jump.state().player.grounded||jump.state().player.jumpVel<=4.0f){std::fprintf(stderr,"SLOPE_FIXTURE_FAIL jump\n");return 1;}for(int i=0;i<8;++i)input(jump,0,0);const float firstJumpVelocity=jump.state().player.jumpVel;input(jump,0,0,false,true);if(jump.state().player.grounded||jump.state().player.jumpVel<=firstJumpVelocity||jump.state().player.airJumpsRemaining!=0){std::fprintf(stderr,"SLOPE_FIXTURE_FAIL double jump\n");return 1;}for(int i=0;i<240&&!jump.state().player.grounded;++i)input(jump,0,0);const auto landedSupport=sampleSlopeSupport(fixture,jump.state().player.pos.x,jump.state().player.pos.z);if(!jump.state().player.grounded||!near(jump.state().player.pos.y,landedSupport.height+0.08f)){std::fprintf(stderr,"SLOPE_FIXTURE_FAIL landing\n");return 1;}
    Game melee;melee.debugStartSlopeLab();placeOnSlope(melee,0,7);input(melee,0,0,false,false,true);if(melee.state().meleeVisual.visualTimer<=0.0f){std::fprintf(stderr,"SLOPE_FIXTURE_FAIL melee\n");return 1;}
    Game vacuum;vacuum.debugStartSlopeLab();placeOnSlope(vacuum,0,7);input(vacuum,0,0,true);if(!vacuum.state().vacuum.active){std::fprintf(stderr,"SLOPE_FIXTURE_FAIL vacuum\n");return 1;}
    Game shot;shot.debugStartSlopeLab();placeOnSlope(shot,0,7);if(!shot.debugSpawnStoredSoul()){std::fprintf(stderr,"SLOPE_FIXTURE_FAIL shot setup\n");return 1;}input(shot,0,0,false,false,false,true);bool pending=false;for(const auto& request:shot.state().pendingShots)pending|=request.active;if(!pending){std::fprintf(stderr,"SLOPE_FIXTURE_FAIL shot\n");return 1;}
    Game lunge;lunge.debugStartSlopeLab();placeOnSlope(lunge,0,7);input(lunge,0,0,false,true);input(lunge,0,0,false,false,true);if(!lunge.state().meleeVisual.airLungeLandingPending){std::fprintf(stderr,"SLOPE_FIXTURE_FAIL lunge\n");return 1;}

    const auto runEnemySlope=[&](float enemyZ,float playerZ,bool ascending){
        auto enemyRun=std::make_unique<Game>();enemyRun->debugStartSlopeLab();auto& state=enemyRun->networkMutableState();
        for(auto& target:state.targets)target=TargetState{};
        RoomCollider& slopeSlot=state.roomColliders[1];slopeSlot.minX=fixture.minX;slopeSlot.maxX=fixture.maxX;slopeSlot.minZ=fixture.minZ;slopeSlot.maxZ=fixture.maxZ;slopeSlot.bottomY=0.0f;slopeSlot.topY=fixture.highHeight;slopeSlot.kind=RoomColliderKind::SlopeAuthoritySlot;state.debug.colliderCount=2;
        const auto playerSupport=sampleSlopeSupport(fixture,0.0f,playerZ);state.player.pos={0.0f,playerSupport.height+0.08f,playerZ};state.player.vel={};state.player.grounded=true;
        TargetState& enemy=state.targets[0];enemy.alive=true;enemy.pos={0.0f,0.08f,enemyZ};enemy.walkTarget=enemy.pos;enemy.armor=2.0f;enemy.attackCooldown=999.0f;
        float extremeY=ascending?enemy.pos.y:fixture.highHeight+0.08f;bool sampledIncline=false;
        for(int frame=0;frame<240;++frame){enemyRun->setTouchControls(0,0,0,0,false,false,false,false,false,false);enemyRun->update(Dt);const auto& observed=enemyRun->state().targets[0];const auto support=sampleSlopeSupport(fixture,observed.pos.x,observed.pos.z);if(support.inside){sampledIncline=true;const float expected=support.height+0.08f;if(!near(observed.pos.y,expected,0.002f)||!std::isfinite(observed.pos.y)){std::fprintf(stderr,"ENEMY_SLOPE_FAIL support direction=%s frame=%d y=%.3f expected=%.3f\n",ascending?"up":"down",frame,observed.pos.y,expected);return false;}extremeY=ascending?std::max(extremeY,observed.pos.y):std::min(extremeY,observed.pos.y);}}
        if(!sampledIncline||(ascending?extremeY<0.60f:extremeY>1.10f)){std::fprintf(stderr,"ENEMY_SLOPE_FAIL progress direction=%s extremeY=%.3f\n",ascending?"up":"down",extremeY);return false;}return true;
    };
    if(!runEnemySlope(11.5f,7.0f,true)||!runEnemySlope(3.0f,7.5f,false))return 1;
    {
        auto edgeRun=std::make_unique<Game>();edgeRun->debugStartSlopeLab();auto& state=edgeRun->networkMutableState();for(auto& target:state.targets)target=TargetState{};for(auto& collider:state.roomColliders)collider=RoomCollider{};
        RoomCollider& slopeSlot=state.roomColliders[0];slopeSlot.minX=fixture.minX;slopeSlot.maxX=fixture.maxX;slopeSlot.minZ=fixture.minZ;slopeSlot.maxZ=fixture.maxZ;slopeSlot.bottomY=0.0f;slopeSlot.topY=fixture.highHeight;slopeSlot.kind=RoomColliderKind::SlopeAuthoritySlot;state.debug.colliderCount=1;
        state.player.pos={0.0f,0.08f,0.0f};state.player.vel={};state.player.grounded=true;TargetState& enemy=state.targets[0];enemy.alive=true;enemy.pos={0.0f,slopeHeightAt(fixture,0.0f,5.0f)+0.08f,5.0f};enemy.walkTarget=enemy.pos;enemy.armor=2.0f;enemy.attackCooldown=999.0f;
        bool departedHighEdge=false,airborne=false,landed=false;float maximumY=enemy.pos.y;
        for(int frame=0;frame<420;++frame){edgeRun->setTouchControls(0,0,0,0,false,false,false,false,false,false);edgeRun->update(Dt);const auto& observed=edgeRun->state().targets[0];maximumY=std::max(maximumY,observed.pos.y);departedHighEdge|=observed.pos.z<fixture.minZ;airborne|=departedHighEdge&&observed.pos.y>0.10f&&observed.vel.y<0.0f;landed|=departedHighEdge&&near(observed.pos.y,0.08f,0.002f)&&near(observed.vel.y,0.0f,0.002f);}
        if(!departedHighEdge||!airborne||!landed||maximumY<1.45f){std::fprintf(stderr,"ENEMY_SLOPE_FAIL high-edge fall departed=%d airborne=%d landed=%d maxY=%.3f\n",departedHighEdge?1:0,airborne?1:0,landed?1:0,maximumY);return 1;}
    }
    {
        auto platformRun=std::make_unique<Game>();platformRun->debugStartSlopeLab();auto& state=platformRun->networkMutableState();for(auto& target:state.targets)target=TargetState{};for(auto& collider:state.roomColliders)collider=RoomCollider{};state.slopeSupportCount=0;state.rockSupportCount=0;
        RoomCollider& platform=state.roomColliders[0];platform.minX=-2.0f;platform.maxX=2.0f;platform.minZ=-1.0f;platform.maxZ=1.0f;platform.bottomY=0.0f;platform.topY=1.0f;state.debug.colliderCount=1;
        state.player.pos={3.5f,0.08f,0.0f};state.player.vel={};state.player.grounded=true;TargetState& enemy=state.targets[0];enemy.alive=true;enemy.pos={0.0f,1.08f,0.0f};enemy.walkTarget=enemy.pos;enemy.armor=2.0f;enemy.attackCooldown=999.0f;
        bool crossedTop=false,departed=false,airborne=false,landed=false;
        for(int frame=0;frame<420;++frame){platformRun->setTouchControls(0,0,0,0,false,false,false,false,false,false);platformRun->update(Dt);const auto& observed=platformRun->state().targets[0];crossedTop|=observed.pos.x>1.0f&&near(observed.pos.y,1.08f,0.002f);departed|=observed.pos.x>2.10f;airborne|=departed&&observed.pos.y>0.10f&&observed.vel.y<0.0f;landed|=departed&&near(observed.pos.y,0.08f,0.002f)&&near(observed.vel.y,0.0f,0.002f);}
        if(!crossedTop||!departed||!airborne||!landed){std::fprintf(stderr,"ENEMY_PLATFORM_FAIL top traversal/fall crossed=%d departed=%d airborne=%d landed=%d\n",crossedTop?1:0,departed?1:0,airborne?1:0,landed?1:0);return 1;}
    }

    Game rock;rock.debugStartSlopeLab();const auto rockAuthority=rock.state().rockSupports[0];const auto& rockProp=rockAuthority.prop;
    if(rock.state().rockSupportCount!=1){std::fprintf(stderr,"ROCK_SUPPORT_FAIL fixture authority\n");return 1;}
    const auto centerSurface=faceted_rock::sampleSupportFootprint(rockAuthority,rockProp.center.x,rockProp.center.z,gameplay::PHONE_BODY.supportRadius);
    const auto centerGameplay=rock.debugPlayerSupportAt(rockProp.center.x,rockProp.center.z);
    if(!centerSurface.inside||!near(centerGameplay.height,centerSurface.height+0.08f)||centerGameplay.normal.y<faceted_rock::WalkableNormalY){std::fprintf(stderr,"ROCK_SUPPORT_FAIL shared facet support\n");return 1;}
    float largestFalseLift=0.0f;Vec3 falseLiftPoint{};
    for(const Vec3& point:walkableRockFaceCenters(rockAuthority)){const auto supportFootprint=faceted_rock::sampleSupportFootprint(rockAuthority,point.x,point.z,gameplay::PHONE_BODY.supportRadius);const auto collisionFootprint=faceted_rock::sampleSupportFootprint(rockAuthority,point.x,point.z,gameplay::PHONE_BODY.collisionRadius);if(supportFootprint.inside&&collisionFootprint.inside&&collisionFootprint.height-supportFootprint.height>largestFalseLift){largestFalseLift=collisionFootprint.height-supportFootprint.height;falseLiftPoint=point;}}
    const auto honestSupport=faceted_rock::sampleSupportFootprint(rockAuthority,falseLiftPoint.x,falseLiftPoint.z,gameplay::PHONE_BODY.supportRadius);const auto honestGameplay=rock.debugPlayerSupportAt(falseLiftPoint.x,falseLiftPoint.z);
    if(largestFalseLift<0.04f||!near(honestGameplay.height,honestSupport.height+0.08f)){std::fprintf(stderr,"ROCK_SUPPORT_FAIL support radius did not prevent collision-clearance lift delta=%.3f\n",largestFalseLift);return 1;}
    const float emptyX=rockProp.center.x+rockProp.size.x*0.5f+gameplay::PHONE_BODY.collisionRadius+0.05f,emptyZ=rockProp.center.z+rockProp.size.z*0.5f+gameplay::PHONE_BODY.collisionRadius+0.05f;
    if(faceted_rock::sampleSupport(rockAuthority,emptyX,emptyZ).inside||!near(rock.debugPlayerSupportAt(emptyX,emptyZ).height,0.08f)){std::fprintf(stderr,"ROCK_SUPPORT_FAIL invisible box top\n");return 1;}
    {
        auto enemyRock=std::make_unique<Game>();enemyRock->debugStartSlopeLab();auto& state=enemyRock->networkMutableState();for(auto& target:state.targets)target=TargetState{};for(auto& collider:state.roomColliders)collider=RoomCollider{};state.slopeSupportCount=0;
        RoomCollider& rockSlot=state.roomColliders[0];rockSlot.minX=rockProp.center.x-rockProp.size.x*0.5f;rockSlot.maxX=rockProp.center.x+rockProp.size.x*0.5f;rockSlot.minZ=rockProp.center.z-rockProp.size.z*0.5f;rockSlot.maxZ=rockProp.center.z+rockProp.size.z*0.5f;rockSlot.bottomY=0.0f;rockSlot.topY=rockProp.size.y*1.04f;rockSlot.kind=RoomColliderKind::RockAuthoritySlot;state.debug.colliderCount=1;
        const auto start=faceted_rock::sampleSupportFootprint(rockAuthority,rockProp.center.x,rockProp.center.z,0.10f);state.player.pos={rockProp.center.x+3.5f,0.08f,rockProp.center.z};state.player.vel={};state.player.grounded=true;TargetState& enemy=state.targets[0];enemy.alive=true;enemy.pos={rockProp.center.x,start.height+0.08f,rockProp.center.z};enemy.walkTarget=enemy.pos;enemy.armor=2.0f;enemy.attackCooldown=999.0f;
        bool crossedFacet=false,leftRock=false,airborne=false,landed=false;
        for(int frame=0;frame<480;++frame){enemyRock->setTouchControls(0,0,0,0,false,false,false,false,false,false);enemyRock->update(Dt);const auto& observed=enemyRock->state().targets[0];const auto support=faceted_rock::sampleSupportFootprint(enemyRock->state().rockSupports[0],observed.pos.x,observed.pos.z,0.10f);const auto worldSupport=enemyRock->debugWorldSupportAt(observed.pos.x,observed.pos.z,0.10f);if(support.inside){crossedFacet|=observed.pos.x>rockProp.center.x+0.45f;const float expected=support.height+0.08f;if(!near(worldSupport.height,expected,0.001f)||observed.pos.y<worldSupport.height-0.01f||observed.pos.y>worldSupport.height+0.02f){std::fprintf(stderr,"ENEMY_ROCK_FAIL facet support frame=%d pos=(%.3f,%.3f) y=%.3f world=%.3f visible=%.3f velY=%.3f\n",frame,observed.pos.x,observed.pos.z,observed.pos.y,worldSupport.height,expected,observed.vel.y);return 1;}}else if(crossedFacet){leftRock=true;airborne|=observed.pos.y>0.10f&&observed.vel.y<0.0f;landed|=near(observed.pos.y,0.08f,0.002f)&&near(observed.vel.y,0.0f,0.002f);}}
        if(!crossedFacet||!leftRock||!landed){std::fprintf(stderr,"ENEMY_ROCK_FAIL supported traversal crossed=%d left=%d airborne=%d landed=%d\n",crossedFacet?1:0,leftRock?1:0,airborne?1:0,landed?1:0);return 1;}
    }
    auto& rockPlayer=rock.networkMutableState().player;rockPlayer.pos={rockProp.center.x,centerGameplay.height,rockProp.center.z};rockPlayer.vel={};rockPlayer.jumpVel=0;rockPlayer.grounded=true;rockPlayer.battery=100;rock.networkMutableState().camera.yaw=-1.5707963f;
    input(rock,0,0,false,true);for(int frame=0;frame<150&&!rock.state().player.grounded;++frame)input(rock,0,0);
    if(!rock.state().player.grounded||!near(rock.state().player.pos.y,centerGameplay.height)||!std::isfinite(rock.state().player.pos.y)){std::fprintf(stderr,"ROCK_SUPPORT_FAIL jump landing\n");return 1;}
    bool leftFacet=false;for(int frame=0;frame<180;++frame){input(rock,0,1);leftFacet|=!faceted_rock::sampleEnvelopeFootprint(rockAuthority,rock.state().player.pos.x,rock.state().player.pos.z,gameplay::PHONE_BODY.collisionRadius).inside;if(rock.state().player.pos.x>rockProp.center.x+rockProp.size.x)break;}
    if(!leftFacet||!std::isfinite(rock.state().player.pos.x)||!std::isfinite(rock.state().player.pos.y)){std::fprintf(stderr,"ROCK_SUPPORT_FAIL traversal/exit\n");return 1;}
    Game rockApproach;rockApproach.debugStartSlopeLab();rockApproach.networkMutableState().slopeSupportCount=0;auto& approachPlayer=rockApproach.networkMutableState().player;approachPlayer.pos={rockProp.center.x-rockProp.size.x,0.08f,rockProp.center.z};approachPlayer.vel={};approachPlayer.grounded=true;approachPlayer.battery=100;rockApproach.networkMutableState().camera.yaw=-1.5707963f;bool approachedSupport=false;float approachHighY=approachPlayer.pos.y,minCameraBoom=99.0f;int onRockFrames=0;for(int frame=0;frame<300;++frame){input(rockApproach,0,1);const auto& state=rockApproach.state();const bool onRock=state.player.supportIdentity.source==SupportSource::Generated;approachedSupport|=onRock;onRockFrames=onRock?onRockFrames+1:0;approachHighY=std::max(approachHighY,state.player.pos.y);if(onRockFrames>10)minCameraBoom=std::min(minCameraBoom,horizontalLength(state.camera.pos-state.player.pos));}if(!approachedSupport||approachHighY<0.30f||rockApproach.state().player.pos.x<rockProp.center.x+0.45f||rockApproach.state().camera.firstPerson||minCameraBoom<1.0f){std::fprintf(stderr,"ROCK_APPROACH_FAIL support=%d highY=%.3f finalX=%.3f firstPerson=%d minBoom=%.3f camera=(%.3f,%.3f,%.3f) player=(%.3f,%.3f,%.3f)\n",approachedSupport?1:0,approachHighY,rockApproach.state().player.pos.x,rockApproach.state().camera.firstPerson?1:0,minCameraBoom,rockApproach.state().camera.pos.x,rockApproach.state().camera.pos.y,rockApproach.state().camera.pos.z,rockApproach.state().player.pos.x,rockApproach.state().player.pos.y,rockApproach.state().player.pos.z);return 1;}
    {
        auto enemyApproach=std::make_unique<Game>();enemyApproach->debugStartSlopeLab();auto& state=enemyApproach->networkMutableState();for(auto& target:state.targets)target=TargetState{};state.slopeSupportCount=0;state.player.pos={rockProp.center.x+2.5f,0.08f,rockProp.center.z};state.player.vel={};state.player.grounded=true;TargetState& enemy=state.targets[0];enemy.alive=true;enemy.pos={rockProp.center.x-2.5f,0.08f,rockProp.center.z};enemy.walkTarget=enemy.pos;enemy.armor=2.0f;enemy.attackCooldown=999.0f;bool gainedRockSupport=false;float furthestX=enemy.pos.x;int stalledFrames=0,maxStalledFrames=0;for(int frame=0;frame<600;++frame){const float before=enemyApproach->state().targets[0].pos.x;enemyApproach->update(Dt);const auto& observed=enemyApproach->state().targets[0];gainedRockSupport|=observed.pos.y>0.12f;furthestX=std::max(furthestX,observed.pos.x);if(std::abs(observed.pos.x-before)<0.0001f)++stalledFrames;else stalledFrames=0;maxStalledFrames=std::max(maxStalledFrames,stalledFrames);}if(!gainedRockSupport||furthestX<rockProp.center.x+0.35f||maxStalledFrames>90){std::fprintf(stderr,"ENEMY_ROCK_APPROACH_FAIL support=%d furthestX=%.3f stall=%d\n",gainedRockSupport?1:0,furthestX,maxStalledFrames);return 1;}
    }
    Game rockCombat;rockCombat.debugStartSlopeLab();auto& combatPlayer=rockCombat.networkMutableState().player;combatPlayer.pos={rockProp.center.x,centerGameplay.height,rockProp.center.z};combatPlayer.vel={};combatPlayer.grounded=true;combatPlayer.battery=100;input(rockCombat,0,0,false,false,true);if(rockCombat.state().meleeVisual.visualTimer<=0){std::fprintf(stderr,"ROCK_SUPPORT_FAIL combat authority\n");return 1;}
    rockCombat.debugStartSlopeLab();auto& vacuumPlayer=rockCombat.networkMutableState().player;vacuumPlayer.pos={rockProp.center.x,centerGameplay.height,rockProp.center.z};vacuumPlayer.vel={};vacuumPlayer.grounded=true;vacuumPlayer.battery=100;input(rockCombat,0,0,true);if(!rockCombat.state().vacuum.active){std::fprintf(stderr,"ROCK_SUPPORT_FAIL vacuum authority\n");return 1;}

    for(int variant=0;variant<12;++variant){
        for(int direction=0;direction<8;++direction){
            auto generated=std::make_unique<Game>();generated->debugStartSlopeLab();auto& generatedState=generated->networkMutableState();auto& generatedRock=generatedState.rockSupports[0];generatedRock.roomSeed=73+variant*97;generatedRock.roomIndex=variant;generatedRock.propIndex=variant+3;generatedRock.prop.yaw=0.19f*variant;
            const float angle=6.283185307f*static_cast<float>(direction)/8.0f;const Vec3 travel{std::cos(angle),0,std::sin(angle)};const auto startSupport=generated->debugPlayerSupportAt(generatedRock.prop.center.x,generatedRock.prop.center.z);auto& generatedPlayer=generatedState.player;generatedPlayer.pos={generatedRock.prop.center.x,startSupport.height,generatedRock.prop.center.z};generatedPlayer.vel={};generatedPlayer.jumpVel=0;generatedPlayer.grounded=true;generatedPlayer.battery=100;generatedState.camera.yaw=std::atan2(-travel.x,-travel.z);
            for(int frame=0;frame<150;++frame){const bool jumpPressed=frame==12;const bool meleePressed=frame==32;const bool vacuumHeld=frame>=52&&frame<76;input(*generated,0,1,vacuumHeld,jumpPressed,meleePressed);const auto& current=generated->state();const float required=denseRockHeight(generatedRock,current.player.pos.x,current.player.pos.z,gameplay::PHONE_BODY.supportRadius);const float bodyBottom=current.player.pos.y-PHONE_BODY_HEIGHT*0.5f;if(required>=0.0f&&bodyBottom<required-0.001f){std::fprintf(stderr,"GENERATED_SURFACE_FAIL body penetration variant=%d direction=%d frame=%d bottom=%.3f surface=%.3f\n",variant,direction,frame,bodyBottom,required);return 1;}const auto visiblePhone=phoneWorldBounds(current);const float visibleSurface=denseRockHeight(generatedRock,current.phoneTransform.position.x,current.phoneTransform.position.z,visiblePhone.horizontalRadius);if(visibleSurface>=0.0f&&visiblePhone.bottom<visibleSurface-0.006f){std::fprintf(stderr,"GENERATED_SURFACE_FAIL visible phone penetration variant=%d direction=%d frame=%d bottom=%.3f surface=%.3f radius=%.3f\n",variant,direction,frame,visiblePhone.bottom,visibleSurface,visiblePhone.horizontalRadius);return 1;}const float cameraSurface=denseRockHeight(generatedRock,current.camera.pos.x,current.camera.pos.z,0.0f);if(cameraSurface>=0.0f&&current.camera.pos.y<cameraSurface+0.02f){std::fprintf(stderr,"GENERATED_SURFACE_FAIL camera penetration variant=%d direction=%d frame=%d cameraY=%.3f surface=%.3f\n",variant,direction,frame,current.camera.pos.y,cameraSurface);return 1;}}

            auto traversal=std::make_unique<Game>();traversal->debugStartSlopeLab();auto& traversalState=traversal->networkMutableState();auto& traversalRock=traversalState.rockSupports[0];traversalRock=generatedRock;const auto traversalStart=traversal->debugPlayerSupportAt(traversalRock.prop.center.x,traversalRock.prop.center.z);auto& traversalPlayer=traversalState.player;traversalPlayer.pos={traversalRock.prop.center.x,traversalStart.height,traversalRock.prop.center.z};traversalPlayer.vel={};traversalPlayer.jumpVel=0;traversalPlayer.grounded=true;traversalPlayer.battery=100;traversalState.camera.yaw=std::atan2(-travel.x,-travel.z);bool leftRock=false;for(int frame=0;frame<240;++frame){input(*traversal,0,1);leftRock|=!faceted_rock::sampleEnvelopeFootprint(traversalRock,traversal->state().player.pos.x,traversal->state().player.pos.z,gameplay::PHONE_BODY.collisionRadius).inside;}const Vec3 displacement=traversal->state().player.pos-Vec3{traversalRock.prop.center.x,traversalStart.height,traversalRock.prop.center.z};if(!leftRock||std::sqrt(displacement.x*displacement.x+displacement.z*displacement.z)<traversalRock.prop.size.x){std::fprintf(stderr,"GENERATED_SURFACE_FAIL controller stuck variant=%d direction=%d pos=(%.3f,%.3f,%.3f)\n",variant,direction,traversal->state().player.pos.x,traversal->state().player.pos.y,traversal->state().player.pos.z);return 1;}
        }
        faceted_rock::Support facetRock=rockAuthority;facetRock.roomSeed=73+variant*97;facetRock.roomIndex=variant;facetRock.propIndex=variant+3;facetRock.prop.yaw=0.19f*variant;
        const auto faceCenters=walkableRockFaceCenters(facetRock);
        for(std::size_t face=0;face<faceCenters.size();++face)for(int heading=0;heading<2;++heading){
            auto facetRun=std::make_unique<Game>();facetRun->debugStartSlopeLab();auto& facetState=facetRun->networkMutableState();facetState.rockSupports[0]=facetRock;const Vec3 start=faceCenters[face];const auto startSupport=facetRun->debugPlayerSupportAt(start.x,start.z);auto& player=facetState.player;player.pos={start.x,startSupport.height,start.z};player.vel={};player.jumpVel=0;player.grounded=true;player.battery=100;const Vec3 radial=normalized(Vec3{start.x-facetRock.prop.center.x,0,start.z-facetRock.prop.center.z});const Vec3 travel=heading==0?radial:Vec3{-radial.z,0,radial.x};facetState.camera.yaw=std::atan2(-travel.x,-travel.z);const Vec3 initial=player.pos;float furthest=0.0f;for(int frame=0;frame<150;++frame){input(*facetRun,0,1);const auto& current=facetRun->state().player;const float dx=current.pos.x-initial.x,dz=current.pos.z-initial.z;furthest=std::max(furthest,std::sqrt(dx*dx+dz*dz));const float required=denseRockHeight(facetRock,current.pos.x,current.pos.z,gameplay::PHONE_BODY.supportRadius);const float bottom=current.pos.y-PHONE_BODY_HEIGHT*0.5f;if(required>=0.0f&&bottom<required-0.001f){std::fprintf(stderr,"GENERATED_SURFACE_FAIL facet penetration variant=%d face=%zu heading=%d frame=%d\n",variant,face,heading,frame);return 1;}}if(furthest<0.75f){std::fprintf(stderr,"GENERATED_SURFACE_FAIL facet stuck variant=%d face=%zu heading=%d progress=%.3f\n",variant,face,heading,furthest);return 1;}
        }
    }
    int productionSeed=-1,productionRoom=-1;
    for(int seed=1;seed<=4096&&productionSeed<0;++seed)for(int room=2;room<=16;++room){const auto plan=early_browser_visuals::roomPlan(seed,room);const auto geometry=early_browser_visuals::roomGeometryCapacityPlan(plan,seed,room,ROOM_COLLIDER_COUNT);for(int surface=0;surface<plan.traversal.surfaceCount;++surface)if(geometry.traversalIncluded[surface]&&early_browser_visuals::usesShallowElevation(plan,plan.traversal.surfaces[surface])){productionSeed=seed;productionRoom=room;break;}if(productionSeed>=0)break;}
    if(productionSeed<0){std::fprintf(stderr,"PRODUCTION_ELEVATION_FAIL no deterministic eligible room\n");return 1;}
    auto production=std::make_unique<Game>();production->debugStartGeneratedRoomFixture(productionSeed,productionRoom);if(production->state().slopeSupportCount!=1){std::fprintf(stderr,"PRODUCTION_ELEVATION_FAIL deployment seed=%d room=%d count=%d\n",productionSeed,productionRoom,production->state().slopeSupportCount);return 1;}
    const auto productionSlope=production->state().slopeSupports[0];if(classifySupport(productionSlope)!=SupportClassification::TraversableSlope||productionSlope.lowHeight!=0.0f||productionSlope.highHeight>0.8f){std::fprintf(stderr,"PRODUCTION_ELEVATION_FAIL bounded shape\n");return 1;}
    const bool positive=productionSlope.axis==SlopeAxis::PositiveX;const float lowX=positive?productionSlope.minX:productionSlope.maxX,highX=positive?productionSlope.maxX:productionSlope.minX,z=(productionSlope.minZ+productionSlope.maxZ)*0.5f;
    auto& productionState=production->networkMutableState();productionState.player.pos={lowX+(positive?-0.7f:0.7f),0.08f,z};productionState.player.vel={};productionState.player.jumpVel=0;productionState.player.grounded=true;productionState.player.battery=100;productionState.camera.yaw=positive?-1.5707963f:1.5707963f;
    bool climbed=false,leftHighEdge=false;float highestY=production->state().player.pos.y;Vec3 priorCamera=production->state().camera.pos;
    for(int frame=0;frame<240;++frame){input(*production,0,1);const auto& state=production->state();highestY=std::max(highestY,state.player.pos.y);climbed|=state.player.supportIdentity.source==SupportSource::Slope;leftHighEdge|=positive?state.player.pos.x>highX+0.2f:state.player.pos.x<highX-0.2f;if(!std::isfinite(state.player.pos.y)||!std::isfinite(state.camera.pos.x)||!std::isfinite(state.camera.pos.y)||!std::isfinite(state.camera.pos.z)||(frame>0&&length(state.camera.pos-priorCamera)>1.0f)){std::fprintf(stderr,"PRODUCTION_ELEVATION_FAIL finite camera/controller frame=%d\n",frame);return 1;}priorCamera=state.camera.pos;}
    if(!climbed||!leftHighEdge||highestY<productionSlope.highHeight*0.7f){std::fprintf(stderr,"PRODUCTION_ELEVATION_FAIL traversal climbed=%d left=%d highY=%.3f\n",climbed?1:0,leftHighEdge?1:0,highestY);return 1;}
    auto productionRepeat=std::make_unique<Game>();productionRepeat->debugStartGeneratedRoomFixture(productionSeed,productionRoom);const auto repeated=productionRepeat->state().slopeSupports[0];if(productionRepeat->state().slopeSupportCount!=1||repeated.minX!=productionSlope.minX||repeated.maxX!=productionSlope.maxX||repeated.minZ!=productionSlope.minZ||repeated.maxZ!=productionSlope.maxZ||repeated.highHeight!=productionSlope.highHeight||repeated.axis!=productionSlope.axis){std::fprintf(stderr,"PRODUCTION_ELEVATION_FAIL nondeterministic deployment\n");return 1;}

    Game normal;normal.reset();ascent.reset();if(normal.state().slopeLab||normal.state().slopeSupportCount!=0){std::fprintf(stderr,"SLOPE_FIXTURE_FAIL leaked into ineligible normal room\n");return 1;}
    if(normal.state().rockSupportCount<=0||normal.state().rockSupportCount>ROCK_SUPPORT_COUNT||normal.state().rockSupportCount!=ascent.state().rockSupportCount){std::fprintf(stderr,"ROCK_SUPPORT_FAIL deterministic room deployment count=%d repeat=%d\n",normal.state().rockSupportCount,ascent.state().rockSupportCount);return 1;}
    int rockSlots=0;for(int i=0;i<normal.state().debug.colliderCount;++i)rockSlots+=normal.state().roomColliders[i].kind==RoomColliderKind::RockAuthoritySlot?1:0;
    if(rockSlots!=normal.state().rockSupportCount){std::fprintf(stderr,"ROCK_SUPPORT_FAIL capacity slots=%d supports=%d\n",rockSlots,normal.state().rockSupportCount);return 1;}
    for(int i=0;i<normal.state().rockSupportCount;++i){const auto& deployed=normal.state().rockSupports[i];const auto plan=early_browser_visuals::roomPlan(normal.state().roomSeed,normal.state().roomIndex);if(!faceted_rock::eligible(plan.setting,deployed.prop.role)||deployed.roomSeed!=normal.state().roomSeed||deployed.roomIndex!=normal.state().roomIndex){std::fprintf(stderr,"ROCK_SUPPORT_FAIL room authority\n");return 1;}const auto visual=faceted_rock::sampleSupportFootprint(deployed,deployed.prop.center.x,deployed.prop.center.z,gameplay::PHONE_BODY.supportRadius);const auto gameplaySupport=normal.debugPlayerSupportAt(deployed.prop.center.x,deployed.prop.center.z);if(!visual.inside||!near(gameplaySupport.height,visual.height+0.08f)){std::fprintf(stderr,"ROCK_SUPPORT_FAIL generated shared facet\n");return 1;}}
    std::printf("SLOPE_FIXTURE_OK approach ascent plateau descent lateral stop reversal jump double-jump landing melee vacuum shot lunge enemy-ascent enemy-descent enemy-high-edge-fall enemy-platform-traversal enemy-supported-rock-traversal camera bounded-speed rock-facet-support rock-jump rock-fall rock-side-obstruction rock-combat no-box-top deterministic-room-rock-deployment generated-surface-controller-sweep facet-start-controller-sweep body-clearance visible-phone-clearance action-sweep camera-clearance production-elevation seed=%d room=%d\n",productionSeed,productionRoom);
    return 0;
}
