#include "Game.hpp"

#include <cmath>
#include <cstdio>
#include <memory>

namespace {
constexpr float Dt=1.0f/60.0f;
void input(Game& game,float x,float z,bool vacuum=false,bool jump=false,bool melee=false,bool shoot=false){game.setTouchControls(x,z,0,0,vacuum,false,jump,melee,shoot,false);game.update(Dt);}
void placeOnSlope(Game& game,float x,float z){auto& state=game.networkMutableState();const auto sample=sampleSlopeSupport(state.slopeSupports[0],x,z);state.player.pos={x,sample.height+0.08f,z};state.player.vel={};state.player.jumpVel=0;state.player.grounded=true;state.player.battery=100;state.camera.yaw=0;}
bool near(float a,float b,float tolerance=0.025f){return std::fabs(a-b)<=tolerance;}
float horizontalSpeed(const Vec3& velocity){return std::sqrt(velocity.x*velocity.x+velocity.z*velocity.z);}
}

int main(){
    Game ascent;ascent.debugStartSlopeLab();const auto fixture=ascent.state().slopeSupports[0];
    if(!ascent.state().slopeLab||ascent.state().slopeSupportCount!=1||ascent.state().debug.colliderCount!=3||classifySupport(fixture)!=SupportClassification::TraversableSlope){std::fprintf(stderr,"SLOPE_FIXTURE_FAIL authority\n");return 1;}
    const auto flatAuthority=ascent.debugPlayerSupportAt(0.0f,13.5f),slopeAuthority=ascent.debugPlayerSupportAt(0.0f,7.0f),plateauAuthority=ascent.debugPlayerSupportAt(0.0f,0.0f);
    if(flatAuthority.source!=SupportSource::Ground||slopeAuthority.source!=SupportSource::Slope||slopeAuthority.sourceIndex!=0||plateauAuthority.source!=SupportSource::Collider||plateauAuthority.sourceIndex!=0){std::fprintf(stderr,"WORLD_CONTACT_FAIL source authority ground=%d slope=%d plateau=%d\n",static_cast<int>(flatAuthority.source),static_cast<int>(slopeAuthority.source),static_cast<int>(plateauAuthority.source));return 1;}
    bool crossedSlope=false,reachedPlateau=false;float previousY=ascent.state().player.pos.y;Vec3 previousCamera=ascent.state().camera.pos;
    for(int frame=0;frame<600;++frame){input(ascent,0,1);const auto& p=ascent.state().player;const Vec3 cameraDelta=ascent.state().camera.pos-previousCamera;if(!std::isfinite(ascent.state().camera.pos.x)||!std::isfinite(ascent.state().camera.pos.y)||!std::isfinite(ascent.state().camera.pos.z)||(frame>0&&length(cameraDelta)>1.0f)||horizontalSpeed(p.vel)>7.0f){std::fprintf(stderr,"SLOPE_FIXTURE_FAIL bounded camera/speed frame=%d\n",frame);return 1;}previousCamera=ascent.state().camera.pos;if(p.pos.z<fixture.maxZ&&p.pos.z>fixture.minZ){const auto support=sampleSlopeSupport(fixture,p.pos.x,p.pos.z);crossedSlope=true;if(!p.grounded||!near(p.pos.y,support.height+0.08f)||p.pos.y+0.001f<previousY){std::fprintf(stderr,"SLOPE_FIXTURE_FAIL ascent frame=%d pos=(%.3f,%.3f,%.3f)\n",frame,p.pos.x,p.pos.y,p.pos.z);return 1;}}previousY=p.pos.y;if(p.pos.z<fixture.minZ-0.3f){reachedPlateau=p.grounded&&near(p.pos.y,1.68f);break;}}
    if(!crossedSlope||!reachedPlateau){const auto& p=ascent.state().player;std::fprintf(stderr,"SLOPE_FIXTURE_FAIL seam ascent crossed=%d plateau=%d pos=(%.3f,%.3f,%.3f) grounded=%d\n",crossedSlope?1:0,reachedPlateau?1:0,p.pos.x,p.pos.y,p.pos.z,p.grounded?1:0);return 1;}

    Game stop;stop.debugStartSlopeLab();placeOnSlope(stop,0,7);for(int i=0;i<45;++i)input(stop,0,1);for(int i=0;i<120;++i)input(stop,0,0);const auto stopped=stop.state().player;const auto stoppedSupport=sampleSlopeSupport(fixture,stopped.pos.x,stopped.pos.z);if(!stopped.grounded||horizontalSpeed(stopped.vel)>0.02f||!near(stopped.pos.y,stoppedSupport.height+0.08f)){std::fprintf(stderr,"SLOPE_FIXTURE_FAIL stopping speed=%.3f\n",horizontalSpeed(stopped.vel));return 1;}

    Game reverse;reverse.debugStartSlopeLab();placeOnSlope(reverse,0,7);for(int i=0;i<24;++i)input(reverse,0,1);const float uphillZ=reverse.state().player.pos.z;for(int i=0;i<24;++i)input(reverse,0,-1);if(reverse.state().player.vel.z<=0||reverse.state().player.pos.z<=uphillZ){std::fprintf(stderr,"SLOPE_FIXTURE_FAIL reversal velZ=%.3f\n",reverse.state().player.vel.z);return 1;}

    Game downhill;downhill.debugStartSlopeLab();placeOnSlope(downhill,0,3);for(int i=0;i<45;++i)input(downhill,0,-1);if(!downhill.state().player.grounded||downhill.state().player.pos.z<=3.5f){std::fprintf(stderr,"SLOPE_FIXTURE_FAIL downhill\n");return 1;}
    Game lateral;lateral.debugStartSlopeLab();placeOnSlope(lateral,0,7);for(int i=0;i<30;++i)input(lateral,1,0);if(!lateral.state().player.grounded||lateral.state().player.pos.x<0.5f||std::fabs(lateral.state().player.pos.z-7)>0.05f){std::fprintf(stderr,"SLOPE_FIXTURE_FAIL lateral pos=(%.3f,%.3f)\n",lateral.state().player.pos.x,lateral.state().player.pos.z);return 1;}

    Game jump;jump.debugStartSlopeLab();placeOnSlope(jump,0,7);input(jump,0,0,false,true);if(jump.state().player.grounded||jump.state().player.jumpVel<=4.0f){std::fprintf(stderr,"SLOPE_FIXTURE_FAIL jump\n");return 1;}for(int i=0;i<8;++i)input(jump,0,0);const float firstJumpVelocity=jump.state().player.jumpVel;input(jump,0,0,false,true);if(jump.state().player.grounded||jump.state().player.jumpVel<=firstJumpVelocity||jump.state().player.airJumpsRemaining!=0){std::fprintf(stderr,"SLOPE_FIXTURE_FAIL double jump\n");return 1;}for(int i=0;i<240&&!jump.state().player.grounded;++i)input(jump,0,0);const auto landedSupport=sampleSlopeSupport(fixture,jump.state().player.pos.x,jump.state().player.pos.z);if(!jump.state().player.grounded||!near(jump.state().player.pos.y,landedSupport.height+0.08f)){std::fprintf(stderr,"SLOPE_FIXTURE_FAIL landing\n");return 1;}
    Game melee;melee.debugStartSlopeLab();placeOnSlope(melee,0,7);input(melee,0,0,false,false,true);if(melee.state().meleeVisual.visualTimer<=0.0f){std::fprintf(stderr,"SLOPE_FIXTURE_FAIL melee\n");return 1;}
    Game vacuum;vacuum.debugStartSlopeLab();placeOnSlope(vacuum,0,7);input(vacuum,0,0,true);if(!vacuum.state().vacuum.active){std::fprintf(stderr,"SLOPE_FIXTURE_FAIL vacuum\n");return 1;}
    Game shot;shot.debugStartSlopeLab();placeOnSlope(shot,0,7);if(!shot.debugSpawnStoredSoul()){std::fprintf(stderr,"SLOPE_FIXTURE_FAIL shot setup\n");return 1;}input(shot,0,0,false,false,false,true);bool pending=false;for(const auto& request:shot.state().pendingShots)pending|=request.active;if(!pending){std::fprintf(stderr,"SLOPE_FIXTURE_FAIL shot\n");return 1;}
    Game lunge;lunge.debugStartSlopeLab();placeOnSlope(lunge,0,7);input(lunge,0,0,false,true);input(lunge,0,0,false,false,true);if(!lunge.state().meleeVisual.airLungeLandingPending){std::fprintf(stderr,"SLOPE_FIXTURE_FAIL lunge\n");return 1;}

    Game rock;rock.debugStartSlopeLab();const auto rockAuthority=rock.state().rockSupports[0];const auto& rockProp=rockAuthority.prop;
    if(rock.state().rockSupportCount!=1){std::fprintf(stderr,"ROCK_SUPPORT_FAIL fixture authority\n");return 1;}
    const auto centerSurface=faceted_rock::sampleSupport(rockAuthority,rockProp.center.x,rockProp.center.z);
    const auto centerGameplay=rock.debugPlayerSupportAt(rockProp.center.x,rockProp.center.z);
    if(!centerSurface.inside||!near(centerGameplay.height,centerSurface.height+0.08f)||centerGameplay.normal.y<faceted_rock::WalkableNormalY||centerGameplay.source!=SupportSource::RockFacet||centerGameplay.sourceIndex!=0){std::fprintf(stderr,"ROCK_SUPPORT_FAIL shared facet support\n");return 1;}
    const float emptyX=rockProp.center.x+rockProp.size.x*0.49f,emptyZ=rockProp.center.z+rockProp.size.z*0.49f;
    if(faceted_rock::sampleSupport(rockAuthority,emptyX,emptyZ).inside||!near(rock.debugPlayerSupportAt(emptyX,emptyZ).height,0.08f)){std::fprintf(stderr,"ROCK_SUPPORT_FAIL invisible box top\n");return 1;}
    auto& rockPlayer=rock.networkMutableState().player;rockPlayer.pos={rockProp.center.x,centerGameplay.height,rockProp.center.z};rockPlayer.vel={};rockPlayer.jumpVel=0;rockPlayer.grounded=true;rockPlayer.battery=100;rock.networkMutableState().camera.yaw=-1.5707963f;
    input(rock,0,0,false,true);for(int frame=0;frame<150&&!rock.state().player.grounded;++frame)input(rock,0,0);
    if(!rock.state().player.grounded||!near(rock.state().player.pos.y,centerGameplay.height)||!std::isfinite(rock.state().player.pos.y)){std::fprintf(stderr,"ROCK_SUPPORT_FAIL jump landing\n");return 1;}
    bool fellFromFacet=false;for(int frame=0;frame<180;++frame){input(rock,0,1);fellFromFacet|=!rock.state().player.grounded;if(rock.state().player.pos.x>rockProp.center.x+rockProp.size.x)break;}
    if(!fellFromFacet||!std::isfinite(rock.state().player.pos.x)||!std::isfinite(rock.state().player.pos.y)){std::fprintf(stderr,"ROCK_SUPPORT_FAIL traversal/fall\n");return 1;}
    Game rockSide;rockSide.debugStartSlopeLab();auto& sidePlayer=rockSide.networkMutableState().player;sidePlayer.pos={rockProp.center.x-rockProp.size.x,0.08f,rockProp.center.z};sidePlayer.vel={};sidePlayer.grounded=true;rockSide.networkMutableState().camera.yaw=-1.5707963f;for(int frame=0;frame<180;++frame)input(rockSide,0,1);const auto sideSupport=faceted_rock::sampleSupport(rockAuthority,rockSide.state().player.pos.x,rockSide.state().player.pos.z);if(sideSupport.inside||rockSide.state().player.pos.x>=rockProp.center.x-rockProp.size.x*0.25f){std::fprintf(stderr,"ROCK_SUPPORT_FAIL steep side obstruction pos=(%.3f,%.3f,%.3f)\n",rockSide.state().player.pos.x,rockSide.state().player.pos.y,rockSide.state().player.pos.z);return 1;}
    Game rockCombat;rockCombat.debugStartSlopeLab();auto& combatPlayer=rockCombat.networkMutableState().player;combatPlayer.pos={rockProp.center.x,centerGameplay.height,rockProp.center.z};combatPlayer.vel={};combatPlayer.grounded=true;combatPlayer.battery=100;input(rockCombat,0,0,false,false,true);if(rockCombat.state().meleeVisual.visualTimer<=0){std::fprintf(stderr,"ROCK_SUPPORT_FAIL combat authority\n");return 1;}
    rockCombat.debugStartSlopeLab();auto& vacuumPlayer=rockCombat.networkMutableState().player;vacuumPlayer.pos={rockProp.center.x,centerGameplay.height,rockProp.center.z};vacuumPlayer.vel={};vacuumPlayer.grounded=true;vacuumPlayer.battery=100;input(rockCombat,0,0,true);if(!rockCombat.state().vacuum.active){std::fprintf(stderr,"ROCK_SUPPORT_FAIL vacuum authority\n");return 1;}

    auto ruin=std::make_unique<Game>();ruin->debugStartSlopeLab();const auto ruinParts=ruin_geometry::parts(ruin->state().geometryProofRuin);const auto bodyBounds=ruin_geometry::bounds(ruinParts[0]),remnantBounds=ruin_geometry::bounds(ruinParts[1]);
    const auto bodySupport=ruin->debugPlayerSupportAt(ruinParts[0].center.x,ruinParts[0].center.z);const auto remnantSupport=ruin->debugPlayerSupportAt(ruinParts[1].center.x,ruinParts[1].center.z);const auto absentUpperSupport=ruin->debugPlayerSupportAt(bodyBounds.minX+0.15f,ruinParts[0].center.z);
    if(!near(bodySupport.height,bodyBounds.topY+0.08f)||!near(remnantSupport.height,remnantBounds.topY+0.08f)||!near(absentUpperSupport.height,bodyBounds.topY+0.08f)){std::fprintf(stderr,"RUIN_GEOMETRY_FAIL stepped support body=%.3f remnant=%.3f absent=%.3f\n",bodySupport.height,remnantSupport.height,absentUpperSupport.height);return 1;}
    auto& ruinPlayer=ruin->networkMutableState().player;ruinPlayer.pos={remnantBounds.maxX+0.34f,remnantBounds.topY-PHONE_MODEL_HEIGHT*0.5f,ruinParts[1].center.z};ruinPlayer.vel={0,0,1.6f};ruinPlayer.jumpVel=-0.8f;ruinPlayer.grounded=false;input(*ruin,0,0);
    if(!ruin->state().player.ledgeHanging||ruin->state().player.ledgeCollider!=2){std::fprintf(stderr,"RUIN_GEOMETRY_FAIL visible remnant ledge catch collider=%d\n",ruin->state().player.ledgeCollider);return 1;}
    ruin->networkMutableState().camera.yaw=1.5707963f;input(*ruin,0,1,false,true);if(ruin->state().player.ledgeHanging||!ruin->state().player.grounded||!near(ruin->state().player.pos.y,remnantBounds.topY+0.08f)||ruin->state().player.ledgeMantleTimer<=0){std::fprintf(stderr,"RUIN_GEOMETRY_FAIL mantle\n");return 1;}

    Game normal;normal.reset();ascent.reset();if(normal.state().slopeLab||normal.state().slopeSupportCount!=0){std::fprintf(stderr,"SLOPE_FIXTURE_FAIL leaked into normal rooms\n");return 1;}
    if(normal.state().rockSupportCount<=0||normal.state().rockSupportCount>ROCK_SUPPORT_COUNT||normal.state().rockSupportCount!=ascent.state().rockSupportCount){std::fprintf(stderr,"ROCK_SUPPORT_FAIL deterministic room deployment count=%d repeat=%d\n",normal.state().rockSupportCount,ascent.state().rockSupportCount);return 1;}
    int rockSlots=0;for(int i=0;i<normal.state().debug.colliderCount;++i)rockSlots+=normal.state().roomColliders[i].kind==RoomColliderKind::RockAuthoritySlot?1:0;
    if(rockSlots!=normal.state().rockSupportCount){std::fprintf(stderr,"ROCK_SUPPORT_FAIL capacity slots=%d supports=%d\n",rockSlots,normal.state().rockSupportCount);return 1;}
    for(int i=0;i<normal.state().rockSupportCount;++i){const auto& deployed=normal.state().rockSupports[i];const auto plan=early_browser_visuals::roomPlan(normal.state().roomSeed,normal.state().roomIndex);if(!faceted_rock::eligible(plan.setting,deployed.prop.role)||deployed.roomSeed!=normal.state().roomSeed||deployed.roomIndex!=normal.state().roomIndex){std::fprintf(stderr,"ROCK_SUPPORT_FAIL room authority\n");return 1;}const auto visual=faceted_rock::sampleSupport(deployed,deployed.prop.center.x,deployed.prop.center.z);const auto gameplaySupport=normal.debugPlayerSupportAt(deployed.prop.center.x,deployed.prop.center.z);if(!visual.inside||!near(gameplaySupport.height,visual.height+0.08f)){std::fprintf(stderr,"ROCK_SUPPORT_FAIL generated shared facet\n");return 1;}}
    std::puts("SLOPE_FIXTURE_OK approach ascent plateau descent lateral stop reversal jump double-jump landing melee vacuum shot lunge camera bounded-speed rock-facet-support rock-jump rock-fall rock-side-obstruction rock-combat no-box-top deterministic-room-rock-deployment ruin-stepped-support ruin-ledge-mantle");
    return 0;
}
